"""initial schema

Revision ID: 62833b6a7c78
Revises: 
Create Date: 2026-05-28 17:12:04.065245
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '62833b6a7c78'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('callbacks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unique_id', sa.String(length=64), nullable=False),
    sa.Column('protocol', sa.String(length=16), nullable=False),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_callbacks_unique_id'), 'callbacks', ['unique_id'], unique=False)
    op.create_table('scans',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('target', sa.Text(), nullable=False),
    sa.Column('scope_json', sa.JSON(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.String(length=64), nullable=False),
    sa.Column('fqdn', sa.String(length=255), nullable=False),
    sa.Column('ips_json', sa.JSON(), nullable=False),
    sa.Column('ports_json', sa.JSON(), nullable=False),
    sa.Column('technology_json', sa.JSON(), nullable=False),
    sa.Column('discovery_method', sa.String(length=64), nullable=False),
    sa.Column('http_available', sa.Boolean(), nullable=False),
    sa.Column('https_available', sa.Boolean(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_fqdn'), 'assets', ['fqdn'], unique=False)
    op.create_index(op.f('ix_assets_scan_id'), 'assets', ['scan_id'], unique=False)
    op.create_table('scan_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.String(length=64), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('module', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_logs_scan_id'), 'scan_logs', ['scan_id'], unique=False)
    op.create_table('endpoints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.String(length=64), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('parameters_json', sa.JSON(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_endpoints_asset_id'), 'endpoints', ['asset_id'], unique=False)
    op.create_index(op.f('ix_endpoints_content_hash'), 'endpoints', ['content_hash'], unique=False)
    op.create_index(op.f('ix_endpoints_scan_id'), 'endpoints', ['scan_id'], unique=False)
    op.create_index(op.f('ix_endpoints_url'), 'endpoints', ['url'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.String(length=64), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=True),
    sa.Column('vuln_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('parameter', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('remediation', sa.Text(), nullable=False),
    sa.Column('cwe', sa.String(length=32), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('cvss_vector', sa.String(length=128), nullable=True),
    sa.Column('scanner', sa.String(length=64), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_endpoint_id'), 'findings', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_findings_scan_id'), 'findings', ['scan_id'], unique=False)
    op.create_index(op.f('ix_findings_severity'), 'findings', ['severity'], unique=False)
    op.create_index(op.f('ix_findings_vuln_type'), 'findings', ['vuln_type'], unique=False)
    op.create_table('exploitations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('technique', sa.String(length=64), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('extracted_data', sa.Text(), nullable=True),
    sa.Column('request_raw', sa.Text(), nullable=True),
    sa.Column('response_raw', sa.Text(), nullable=True),
    sa.Column('screenshot_path', sa.Text(), nullable=True),
    sa.Column('callback_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exploitations_callback_id'), 'exploitations', ['callback_id'], unique=False)
    op.create_index(op.f('ix_exploitations_finding_id'), 'exploitations', ['finding_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exploitations_finding_id'), table_name='exploitations')
    op.drop_index(op.f('ix_exploitations_callback_id'), table_name='exploitations')
    op.drop_table('exploitations')
    op.drop_index(op.f('ix_findings_vuln_type'), table_name='findings')
    op.drop_index(op.f('ix_findings_severity'), table_name='findings')
    op.drop_index(op.f('ix_findings_scan_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_endpoint_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_endpoints_url'), table_name='endpoints')
    op.drop_index(op.f('ix_endpoints_scan_id'), table_name='endpoints')
    op.drop_index(op.f('ix_endpoints_content_hash'), table_name='endpoints')
    op.drop_index(op.f('ix_endpoints_asset_id'), table_name='endpoints')
    op.drop_table('endpoints')
    op.drop_index(op.f('ix_scan_logs_scan_id'), table_name='scan_logs')
    op.drop_table('scan_logs')
    op.drop_index(op.f('ix_assets_scan_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_fqdn'), table_name='assets')
    op.drop_table('assets')
    op.drop_table('scans')
    op.drop_index(op.f('ix_callbacks_unique_id'), table_name='callbacks')
    op.drop_table('callbacks')
    # ### end Alembic commands ###
