"""WAF detection (PRD §5.3).

Identifies web application firewalls from response headers, cookies, and body
signatures (passive), enriching the seed asset with a WAF technology tag. The
pure ``detect_waf`` matcher is unit-tested.
"""

from __future__ import annotations

import re
from collections.abc import AsyncIterator
from urllib.parse import urlsplit

import httpx

from orthrus.core import schemas
from orthrus.core.context import ScanContext
from orthrus.core.schemas import Confidence, Technology
from orthrus.recon.base import BaseRecon
from orthrus.utils.logger import get_logger
from orthrus.utils.scope import ScopeViolation

logger = get_logger("recon.waf")

# WAF -> (header-name substrings, header-value regex, cookie-name substrings, body regex)
_SIGNATURES: list[tuple[str, dict]] = [
    ("Cloudflare", {"headers": ["cf-ray", "cf-cache-status"], "server": "cloudflare",
                    "cookies": ["__cfduid", "__cf_bm"], "body": r"Attention Required! \| Cloudflare"}),
    ("Akamai", {"headers": ["x-akamai-transformed", "akamai-grn"], "server": "akamaighost"}),
    ("AWS WAF/ELB", {"headers": ["x-amzn-requestid", "x-amz-cf-id"], "cookies": ["awsalb", "awsalbcors"]}),
    ("Imperva Incapsula", {"headers": ["x-iinfo", "x-cdn"], "cookies": ["incap_ses", "visid_incap"],
                           "body": r"Incapsula incident ID"}),
    ("Sucuri", {"headers": ["x-sucuri-id", "x-sucuri-cache"], "server": "sucuri",
                "body": r"Sucuri WebSite Firewall"}),
    ("ModSecurity", {"server": "mod_security", "body": r"Mod_Security|This error was generated by Mod_Security"}),
    ("F5 BIG-IP", {"cookies": ["bigipserver", "ts01"], "server": "big-?ip"}),
    ("Barracuda", {"cookies": ["barra_counter_session"], "body": r"Barracuda"}),
    ("Fortinet FortiWeb", {"cookies": ["fortiwafsid"], "body": r"FORTIWAFSID"}),
]


def detect_waf(headers: dict[str, str], cookie_names: list[str], body: str) -> str | None:
    lower_headers = {k.lower(): v.lower() for k, v in headers.items()}
    server = lower_headers.get("server", "")
    cookies = " ".join(cookie_names).lower()
    for name, sig in _SIGNATURES:
        if any(h in lower_headers for h in sig.get("headers", [])):
            return name
        if sig.get("server") and re.search(sig["server"], server):
            return name
        if any(c in cookies for c in sig.get("cookies", [])):
            return name
        if sig.get("body") and re.search(sig["body"], body, re.IGNORECASE):
            return name
    return None


class WafDetect(BaseRecon):
    name = "waf-detect"

    async def discover(self, ctx: ScanContext) -> AsyncIterator[schemas.Asset]:
        target = ctx.config.target
        host = (urlsplit(target if "://" in target else f"//{target}").hostname or target).lower()
        if not ctx.scope.is_allowed(target):
            return
        try:
            resp = await ctx.http.get(target)
        except (ScopeViolation, httpx.HTTPError, httpx.InvalidURL):
            return

        body = resp.text if "text" in resp.headers.get("content-type", "") else ""
        waf = detect_waf(dict(resp.headers), resp.headers.get_list("set-cookie"), body)
        if waf:
            logger.info("WAF detected: %s", waf)
            yield schemas.Asset(
                fqdn=host,
                discovery_method="waf-detect",
                technologies=[Technology(name=waf, category="waf", confidence=Confidence.FIRM)],
            )


__all__ = ["WafDetect", "detect_waf"]
