"""Scanner package.

Importing this package registers all built-in scanners with the registry via
their ``@register`` decorators (import side-effects below). New scanner modules
should be added here so the orchestrator can discover them.
"""

from orthrus.scanners import (  # noqa: F401  (registration side-effects)
    account_enum,
    api_misconfig,
    auth,
    authz_matrix,
    business_logic,
    bypass_403,
    cache_poisoning,
    cmd_injection,
    cors,
    crlf,
    csp_analyzer,
    csrf,
    csv_injection,
    cve_matcher,
    default_creds,
    dependency_confusion,
    deserialization,
    directory_listing,
    dom_taint,
    dom_xss,
    email_auth,
    exposed_files,
    file_upload,
    framework_debug,
    graphql,
    graphql_injection,
    grpc_probe,
    headers,
    host_header,
    idor,
    internal_exposure,
    jwt_analyzer,
    ldap,
    lfi,
    llm,
    mass_assignment,
    mixed_content,
    nosql,
    oauth_flow,
    open_redirect,
    origin_exposure,
    otp_2fa,
    password_reset,
    privilege_escalation,
    product_cve,
    prototype_pollution,
    race_condition,
    rate_limit,
    request_smuggling,
    saml,
    sca,
    secret_scanner,
    service_exposure,
    session_fixation,
    shadow_api,
    sqli,
    sri,
    sspp,
    ssrf,
    ssti,
    stored_xss,
    subdomain_takeover,
    tls_analyzer,
    web_cache_deception,
    websocket,
    xpath,
    xss,
    xxe,
)
from orthrus.templates import (
    scanner as _template_scanner,  # noqa: F401  (registers TemplateScanner)
)
