"""Platform-native report templates (PRD §7.6).

The generic submission report (`report.render_submission`) is fine, but each
platform has its own field set and severity language. These renderers shape a bug
the way HackerOne / Bugcrowd / Intigriti / YesWeHack / Immunefi expect it, so you
paste it straight into their form:

* **HackerOne** — Weakness (CWE) + severity rating; Summary / Steps / Impact.
* **Bugcrowd** — Priority **P1–P5** + a VRT hint; Description / Steps / Impact.
* **Intigriti** — severity tier + type; Description / PoC / Impact / Recommendation.
* **YesWeHack** — bug type + CVSS; Description / Steps / Impact.
* **Immunefi** — severity + a reminder that the PoC must be a public gist.

Where a platform uses a taxonomy ORTHRUS can't infer exactly (Bugcrowd VRT,
Intigriti type), the template gives the CWE and tells you to pick the matching
category — it never fabricates one.
"""

from __future__ import annotations

from orthrus.bounty.report import BugGroup, _conf, _norm_title, _sev
from orthrus.reporting.reproduce import build_snippets

PLATFORMS = ("generic", "hackerone", "bugcrowd", "intigriti", "yeswehack", "immunefi")

# Bugcrowd priority (P1 worst) from our severity band.
_BUGCROWD_PRIORITY = {"critical": "P1", "high": "P2", "medium": "P3", "low": "P4", "info": "P5"}

_IMPACT = {
    "critical": "Full compromise of the asset or its data is achievable.",
    "high": "A remote attacker can seriously abuse this against users or data.",
    "medium": "Exploitable under realistic conditions with meaningful impact.",
    "low": "Limited impact; still weakens the asset's security posture.",
    "info": "Informational — a hardening opportunity.",
}


def _cvss(f) -> str:
    return f"{f.cvss_score} ({f.cvss_vector})" if f.cvss_score is not None else "not scored"


def _repro(f) -> list[str]:
    """Shared 'steps to reproduce' block, with curl / Python / raw request."""
    out: list[str] = []
    if f.parameter:
        out.append(f"1. Target the `{f.parameter}` parameter at `{f.url}`.")
    out.append("2. Send the request below; observe the indicator under Evidence.")
    snip = build_snippets(url=f.url, request_raw=getattr(f.evidence, "request_raw", None))
    if snip:
        out += ["", "```bash", snip["curl"], "```",
                "", "<details><summary>Python / raw request (Burp Repeater)</summary>",
                "", "```python", snip["python"], "```",
                "", "```http", snip["raw"], "```", "</details>"]
    else:
        out.append(f"\nRequest the affected URL directly: `{f.url}`")
    return out


def _evidence(f) -> list[str]:
    out: list[str] = []
    ev = f.evidence
    if getattr(ev, "matched_at", None):
        out.append(f"- Indicator: `{str(ev.matched_at)[:300]}`")
    if getattr(ev, "notes", None):
        out.append(f"- {str(ev.notes)[:400]}")
    if getattr(ev, "response_raw", None):
        out.append("\n```http\n" + str(ev.response_raw)[:1200] + "\n```")
    return out


def _affected(group: BugGroup) -> list[str]:
    if len(group.instances) <= 1:
        return []
    locs = "\n".join(f"- `{i.url}`" + (f" (parameter `{i.parameter}`)" if i.parameter else "")
                     for i in group.instances[:25])
    return [f"\n**Affected locations ({len(group.instances)}):**", locs]


def _footer() -> str:
    return ("\n---\n_Generated by ORTHRUS. Confirm the target is in the program's current scope and "
            "follow its disclosure rules before submitting; confirmation was non-destructive._\n")


def _proof_note(f) -> str:
    conf = _conf(f.confidence)
    return f" (re-proven / {conf})" if conf == "confirmed" else f" ({conf})"


def render(group: BugGroup, *, platform: str = "generic", program_name: str = "",
           prior_seen: int = 0) -> str:
    """Render one bug for the given platform; falls back to the generic report.

    ``prior_seen`` > 0 adds a duplicate-warning note (bug matched earlier runs).
    """
    platform = (platform or "generic").lower()
    if platform not in PLATFORMS or platform == "generic":
        from orthrus.bounty.report import render_submission
        return render_submission(group, program_name, prior_seen=prior_seen)

    f = group.lead
    sev = _sev(f.severity)
    title = _norm_title(f.title)
    prog = f"**Program:** {program_name}  \n" if program_name else ""
    body = [f"# {title}", ""]
    if prior_seen > 0:
        runs = "run" if prior_seen == 1 else "runs"
        body += [f"> ♻ **Seen before** — matches a finding from {prior_seen} earlier {runs}; "
                 "verify it isn't already reported before filing.", ""]

    if platform == "hackerone":
        body += [
            prog + f"**Weakness:** {f.cwe or 'n/a'}",
            f"**Severity:** {sev.capitalize()} — CVSS {_cvss(f)}",
            f"**Asset:** {f.url}{_proof_note(f)}",
            "", "## Summary", f.description or f"A {f.vuln_type} issue on the affected asset.",
            *_affected(group),
            "", "## Steps To Reproduce", *_repro(f),
            "", "## Impact", _IMPACT.get(sev, "See summary."),
        ]
        ev = _evidence(f)
        if ev:
            body += ["", "## Supporting Material / References", *ev]
        body += ["", "## Remediation", f.remediation or "Apply standard mitigations for this class."]

    elif platform == "bugcrowd":
        body += [
            prog + f"**Priority:** {_BUGCROWD_PRIORITY.get(sev, 'P3')} ({sev.capitalize()})",
            f"**Bug type:** map to the closest Bugcrowd **VRT** category · CWE {f.cwe or 'n/a'}",
            f"**CVSS:** {_cvss(f)}",
            f"**Affected URL:** {f.url}{_proof_note(f)}",
            "", "## Description", f.description or f"A {f.vuln_type} issue on the affected asset.",
            *_affected(group),
            "", "## Steps to Reproduce", *_repro(f),
            "", "## Impact", _IMPACT.get(sev, "See summary."),
            "", "## Remediation", f.remediation or "Apply standard mitigations for this class.",
        ]

    elif platform == "intigriti":
        body += [
            prog + f"**Severity:** {sev.capitalize()} (CVSS {_cvss(f)})",
            f"**Type:** {f.cwe or 'n/a'} · {getattr(f, 'owasp', None) or ''}".rstrip(" ·"),
            f"**Endpoint:** {f.url}{_proof_note(f)}",
            "", "## Description", f.description or f"A {f.vuln_type} issue on the affected asset.",
            *_affected(group),
            "", "## Proof of concept", *_repro(f),
            "", "## Impact", _IMPACT.get(sev, "See summary."),
            "", "## Recommendation", f.remediation or "Apply standard mitigations for this class.",
        ]

    elif platform == "yeswehack":
        body += [
            prog + f"**Bug type:** {f.cwe or 'n/a'}",
            f"**CVSS:** {_cvss(f)} ({sev.capitalize()})",
            f"**Scope:** {f.url}{_proof_note(f)}",
            "", "## Description", f.description or f"A {f.vuln_type} issue on the affected asset.",
            *_affected(group),
            "", "## Steps to reproduce", *_repro(f),
            "", "## Impact", _IMPACT.get(sev, "See summary."),
            "", "## Remediation", f.remediation or "Apply standard mitigations for this class.",
        ]

    elif platform == "immunefi":
        body += [
            prog + f"**Severity:** {sev.capitalize()} — CVSS {_cvss(f)}",
            f"**Vulnerability type:** {f.cwe or 'n/a'}",
            f"**Asset:** {f.url}{_proof_note(f)}",
            "", "## Description", f.description or f"A {f.vuln_type} issue on the affected asset.",
            "", "## Impact", _IMPACT.get(sev, "See summary."),
            "", "## Proof of Concept",
            "> Immunefi requires the PoC as a **public GitHub gist** — paste the steps below into a "
            "gist and link it here.", "", *_repro(f),
            "", "## Recommendation", f.remediation or "Apply standard mitigations for this class.",
        ]

    return "\n".join(body) + "\n" + _footer()


__all__ = ["PLATFORMS", "render"]
