"""Tests for WAF / API / Wayback / Nmap pure helpers."""

from __future__ import annotations

from orthrus.recon.api_discovery import looks_like_api_spec
from orthrus.recon.port_scan import parse_nmap
from orthrus.recon.waf_detect import detect_waf
from orthrus.recon.wayback import parse_wayback


def test_detect_cloudflare_header():
    assert detect_waf({"CF-RAY": "abc", "Server": "cloudflare"}, [], "") == "Cloudflare"


def test_detect_incapsula_cookie():
    assert detect_waf({}, ["incap_ses_123=x"], "") == "Imperva Incapsula"


def test_detect_modsecurity_body():
    assert detect_waf({}, [], "This error was generated by Mod_Security") == "ModSecurity"


def test_detect_no_waf():
    assert detect_waf({"Server": "nginx"}, ["sid=1"], "<html>ok</html>") is None


def test_api_spec_detection():
    assert looks_like_api_spec('{"openapi":"3.0.0","paths":{"/x":{}}}') is True
    assert looks_like_api_spec('{"swagger":"2.0","paths":{}}') is True
    assert looks_like_api_spec("<html>not a spec</html>") is False


def test_parse_wayback():
    rows = [["original"], ["https://t.com/a"], ["https://t.com/b#frag"], ["ftp://x"]]
    urls = parse_wayback(rows)
    assert urls == ["https://t.com/a", "https://t.com/b"]


def test_parse_nmap():
    scan = {
        "scan": {
            "10.0.0.1": {
                "tcp": {
                    22: {"state": "open"},
                    80: {"state": "open"},
                    81: {"state": "closed"},
                }
            }
        }
    }
    assert parse_nmap(scan) == [("10.0.0.1", [22, 80])]
