"""Pre-engagement scope-briefing generator (orthrus scope-report)."""

from __future__ import annotations

from orthrus.bounty.scope_report import parse_h1_scope_csv, render_scope_report

# a HackerOne-shaped scope CSV with the multi-line quoted instruction fields H1 emits.
CSV = (
    "identifier,asset_type,instruction,eligible_for_bounty,eligible_for_submission,"
    "availability_requirement,confidentiality_requirement,integrity_requirement,max_severity\n"
    '1win.com,URL,"- Registration\n- Login\n- Deposit\n- Withdrawal\n'
    '- Personal account(settings, voucher, details)\n\n'
    '**list of countries where the 1win.com website is available: Brazil, India, Japan**",'
    "true,true,high,high,high,critical\n"
    'https://1win.com/casino,URL,"All casino games are in scope.",true,true,high,high,high,critical\n'
    'Deposit/Withdraw,OTHER,"In scope:\n- Payment forms hosted on 1win.com\n'
    'Out of scope:\n- APIs of external payment providers",true,true,high,high,high,critical\n'
    'archive.example.com,URL,"legacy",false,false,low,low,low,low\n'
)


def test_parse_h1_scope_csv():
    assets = parse_h1_scope_csv(CSV)
    assert len(assets) == 4
    main = assets[0]
    assert main.identifier == "1win.com" and main.asset_type == "URL"
    assert main.eligible_for_bounty is True and main.max_severity == "critical"
    assert main.host == "1win.com"
    assert assets[1].host == "1win.com"                 # from the https:// URL
    assert assets[2].host == ""                          # 'Deposit/Withdraw' is not a host
    assert assets[3].eligible_for_bounty is False        # archive is not bounty-eligible


def test_render_scope_report_sections():
    md = render_scope_report(parse_h1_scope_csv(CSV), source_name="scopes.csv")
    # title + primary host inferred from the most common in-scope host
    assert md.startswith("# 1win.com Bug Bounty Program Scope Report")
    assert "Generated by ORTHRUS from `scopes.csv`" in md
    # components lifted from the bullet list
    for comp in ("Registration", "Login", "Deposit", "Withdrawal"):
        assert f"**{comp}**" in md
    # availability countries extracted
    assert "Available in 3 countries" in md and "Brazil" in md and "Japan" in md
    # in/out technical scope split
    assert "In scope: Payment forms hosted on 1win.com" in md
    assert "Out of scope: APIs of external payment providers" in md
    # program CIA + severity bar
    assert "Confidentiality requirement:** High" in md
    assert "Max severity:** Critical" in md
    # the out-of-scope, non-eligible asset is not listed as in-scope
    assert "archive.example.com" not in md
    # suggested testing focus mapped from the scope language
    assert "Suggested ORTHRUS testing focus" in md
    assert "Payment / transaction flows" in md and "Authentication & session" in md
    # next steps + the safety footer
    assert "## Next Steps" in md
    assert "never touch out-of-scope infrastructure" in md


def test_empty_and_program_override():
    assert "No scope entries parsed" in render_scope_report([])
    md = render_scope_report(parse_h1_scope_csv(CSV), program_name="1win (H1)")
    assert md.startswith("# 1win (H1) Bug Bounty Program Scope Report")
