"""v2 operator graph

Revision ID: 45383fa3d7fd
Revises: 7f2a9c1d4b30
Create Date: 2026-07-20 16:08:54.599899
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '45383fa3d7fd'
down_revision: str | None = '7f2a9c1d4b30'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=True),
    sa.Column('subject_id', sa.String(length=64), nullable=True),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('programs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('authorization_source', sa.Text(), nullable=False),
    sa.Column('policy_url', sa.Text(), nullable=True),
    sa.Column('authorized_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reward_range', sa.JSON(), nullable=False),
    sa.Column('rules_of_engagement_md', sa.Text(), nullable=True),
    sa.Column('rate_limit_hint', sa.JSON(), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('notes_md', sa.Text(), nullable=True),
    sa.Column('is_paused', sa.Boolean(), nullable=False),
    sa.Column('is_read_only', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('jurisdiction', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programs_name'), 'programs', ['name'], unique=False)
    op.create_table('cost_ledger',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('program_id', sa.String(length=32), nullable=True),
    sa.Column('scan_run_id', sa.String(length=32), nullable=True),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_ledger_program_id'), 'cost_ledger', ['program_id'], unique=False)
    op.create_table('scan_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('program_id', sa.String(length=32), nullable=False),
    sa.Column('workflow_id', sa.String(length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('config_snapshot', sa.JSON(), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('triggered_by', sa.String(length=24), nullable=False),
    sa.Column('triggered_by_user', sa.String(length=128), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_runs_program_id'), 'scan_runs', ['program_id'], unique=False)
    op.create_index(op.f('ix_scan_runs_status'), 'scan_runs', ['status'], unique=False)
    op.create_table('scope_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('program_id', sa.String(length=32), nullable=False),
    sa.Column('entry_type', sa.String(length=4), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('ports', sa.JSON(), nullable=True),
    sa.Column('protocols', sa.JSON(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('added_by', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scope_entries_program_id'), 'scope_entries', ['program_id'], unique=False)
    op.create_table('program_assets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('program_id', sa.String(length=32), nullable=False),
    sa.Column('scope_entry_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('canonical_value', sa.Text(), nullable=False),
    sa.Column('display_value', sa.Text(), nullable=False),
    sa.Column('parent_asset_id', sa.String(length=32), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_alive_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_alive', sa.Boolean(), nullable=False),
    sa.Column('is_historical', sa.Boolean(), nullable=False),
    sa.Column('is_ephemeral', sa.Boolean(), nullable=False),
    sa.Column('is_wildcard_noise', sa.Boolean(), nullable=False),
    sa.Column('fingerprint', sa.JSON(), nullable=False),
    sa.Column('screenshot_path', sa.Text(), nullable=True),
    sa.Column('response_hash', sa.String(length=64), nullable=True),
    sa.Column('dom_hash', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('discovered_by', sa.String(length=64), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['parent_asset_id'], ['program_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scope_entry_id'], ['scope_entries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'kind', 'canonical_value', name='uq_asset_identity')
    )
    op.create_index(op.f('ix_program_assets_canonical_value'), 'program_assets', ['canonical_value'], unique=False)
    op.create_index(op.f('ix_program_assets_kind'), 'program_assets', ['kind'], unique=False)
    op.create_index(op.f('ix_program_assets_program_id'), 'program_assets', ['program_id'], unique=False)
    op.create_table('program_endpoints',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('asset_id', sa.String(length=32), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('query_params', sa.JSON(), nullable=False),
    sa.Column('body_params', sa.JSON(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_content_type', sa.String(length=128), nullable=True),
    sa.Column('response_size', sa.Integer(), nullable=True),
    sa.Column('is_authenticated', sa.Boolean(), nullable=True),
    sa.Column('requires_csrf', sa.Boolean(), nullable=True),
    sa.Column('auth_scheme', sa.String(length=16), nullable=True),
    sa.Column('juicy_score', sa.Float(), nullable=True),
    sa.Column('last_probed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('probe_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['program_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_endpoints_asset_id'), 'program_endpoints', ['asset_id'], unique=False)
    op.create_table('program_findings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('program_id', sa.String(length=32), nullable=False),
    sa.Column('asset_id', sa.String(length=32), nullable=True),
    sa.Column('endpoint_id', sa.String(length=32), nullable=True),
    sa.Column('scan_run_id', sa.String(length=32), nullable=True),
    sa.Column('parent_finding_id', sa.String(length=32), nullable=True),
    sa.Column('duplicate_of', sa.String(length=32), nullable=True),
    sa.Column('vuln_class', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description_md', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.String(length=24), nullable=False),
    sa.Column('signature', sa.String(length=255), nullable=False),
    sa.Column('cvss_v3_vector', sa.String(length=128), nullable=True),
    sa.Column('cvss_v3_score', sa.Float(), nullable=True),
    sa.Column('cvss_v4_vector', sa.String(length=160), nullable=True),
    sa.Column('cvss_v4_score', sa.Float(), nullable=True),
    sa.Column('epss_score', sa.Float(), nullable=True),
    sa.Column('kev_flag', sa.Boolean(), nullable=False),
    sa.Column('cwe_id', sa.String(length=32), nullable=True),
    sa.Column('owasp_id', sa.String(length=32), nullable=True),
    sa.Column('capec_ids', sa.JSON(), nullable=False),
    sa.Column('mitre_attack_ids', sa.JSON(), nullable=False),
    sa.Column('mitre_d3fend_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('llm_fp_confidence', sa.Float(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rewarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('found_by_tool', sa.String(length=64), nullable=False),
    sa.Column('bounty_amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('hunter_notes_md', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['program_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['endpoint_id'], ['program_endpoints.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_findings_program_id'), 'program_findings', ['program_id'], unique=False)
    op.create_index(op.f('ix_program_findings_severity'), 'program_findings', ['severity'], unique=False)
    op.create_index(op.f('ix_program_findings_signature'), 'program_findings', ['signature'], unique=False)
    op.create_index(op.f('ix_program_findings_status'), 'program_findings', ['status'], unique=False)
    op.create_index(op.f('ix_program_findings_vuln_class'), 'program_findings', ['vuln_class'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('finding_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('content_ref', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_redacted', sa.Boolean(), nullable=False),
    sa.Column('redaction_map', sa.JSON(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['finding_id'], ['program_findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_content_hash'), 'evidence', ['content_hash'], unique=False)
    op.create_index(op.f('ix_evidence_finding_id'), 'evidence', ['finding_id'], unique=False)
    op.create_table('finding_chains',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('from_finding_id', sa.String(length=32), nullable=False),
    sa.Column('to_finding_id', sa.String(length=32), nullable=False),
    sa.Column('relationship', sa.String(length=24), nullable=False),
    sa.Column('narrative_md', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('proposed_by', sa.String(length=16), nullable=False),
    sa.Column('accepted_by_user', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['from_finding_id'], ['program_findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_finding_id'], ['program_findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_finding_id', 'to_finding_id', 'relationship', name='uq_chain_edge')
    )
    op.create_index(op.f('ix_finding_chains_from_finding_id'), 'finding_chains', ['from_finding_id'], unique=False)
    op.create_index(op.f('ix_finding_chains_to_finding_id'), 'finding_chains', ['to_finding_id'], unique=False)
    op.add_column('assets', sa.Column('ip_intel_json', sa.JSON(), nullable=True))
    # server_default so ADD COLUMN succeeds on an already-populated findings table
    # (matches the model's Python-side default="open").
    op.add_column('findings', sa.Column('status', sa.String(length=24),
                                        nullable=False, server_default='open'))
    op.add_column('findings', sa.Column('owner', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_findings_status'), 'findings', ['status'], unique=False)
    op.add_column('scans', sa.Column('phase', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'phase')
    op.drop_index(op.f('ix_findings_status'), table_name='findings')
    op.drop_column('findings', 'owner')
    op.drop_column('findings', 'status')
    op.drop_column('assets', 'ip_intel_json')
    op.drop_index(op.f('ix_finding_chains_to_finding_id'), table_name='finding_chains')
    op.drop_index(op.f('ix_finding_chains_from_finding_id'), table_name='finding_chains')
    op.drop_table('finding_chains')
    op.drop_index(op.f('ix_evidence_finding_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_content_hash'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_program_findings_vuln_class'), table_name='program_findings')
    op.drop_index(op.f('ix_program_findings_status'), table_name='program_findings')
    op.drop_index(op.f('ix_program_findings_signature'), table_name='program_findings')
    op.drop_index(op.f('ix_program_findings_severity'), table_name='program_findings')
    op.drop_index(op.f('ix_program_findings_program_id'), table_name='program_findings')
    op.drop_table('program_findings')
    op.drop_index(op.f('ix_program_endpoints_asset_id'), table_name='program_endpoints')
    op.drop_table('program_endpoints')
    op.drop_index(op.f('ix_program_assets_program_id'), table_name='program_assets')
    op.drop_index(op.f('ix_program_assets_kind'), table_name='program_assets')
    op.drop_index(op.f('ix_program_assets_canonical_value'), table_name='program_assets')
    op.drop_table('program_assets')
    op.drop_index(op.f('ix_scope_entries_program_id'), table_name='scope_entries')
    op.drop_table('scope_entries')
    op.drop_index(op.f('ix_scan_runs_status'), table_name='scan_runs')
    op.drop_index(op.f('ix_scan_runs_program_id'), table_name='scan_runs')
    op.drop_table('scan_runs')
    op.drop_index(op.f('ix_cost_ledger_program_id'), table_name='cost_ledger')
    op.drop_table('cost_ledger')
    op.drop_index(op.f('ix_programs_name'), table_name='programs')
    op.drop_table('programs')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
