"""notes table

Revision ID: 9a6532b7cbfe
Revises: 45383fa3d7fd
Create Date: 2026-07-21 10:14:52.603534
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '9a6532b7cbfe'
down_revision: str | None = '45383fa3d7fd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('program_id', sa.String(length=32), nullable=True),
    sa.Column('asset_id', sa.String(length=32), nullable=True),
    sa.Column('finding_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('markdown', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['program_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['finding_id'], ['program_findings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_program_id'), 'notes', ['program_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notes_program_id'), table_name='notes')
    op.drop_table('notes')
    # ### end Alembic commands ###
